### ISSUE TITLE
None of the Next.js examples are working.

### ISSUE THREAD

**Issue by ChrisCates** [WalletConnect/web3modal-examples#21]
## Problem

None of the Next.js examples are working. Gives very obtuse weird errors only maintainers will be able to debug.

## Steps to reproduce

```bash
node --version
v18.15.0

npm --version
9.5.0

yarn --version
1.22.19
```

On any Next.js project in this repo run

```
yarn
yarn dev
```

Navigate to localhost... Receive the obtuse stack trace provided below.

## Full Stack Trace

```console
dex.js:638 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at eval (index.es.js:1:918)
    at ./node_modules/@walletconnect/types/dist/index.es.js (index.js?ts=1687365061359:918:1)
    at options.factory (webpack.js?ts=1687365061359:677:31)
    at __webpack_require__ (webpack.js?ts=1687365061359:37:33)
    at fn (webpack.js?ts=1687365061359:332:21)
    at eval (index.es.js:68:78)
    at ./node_modules/@walletconnect/core/dist/index.es.js (index.js?ts=1687365061359:216:1)
    at options.factory (webpack.js?ts=1687365061359:677:31)
    at __webpack_require__ (webpack.js?ts=1687365061359:37:33)
    at fn (webpack.js?ts=1687365061359:332:21)
    at eval (index.es.js:27:77)
    at ./node_modules/@walletconnect/sign-client/dist/index.es.js (index.js?ts=1687365061359:797:1)
    at options.factory (webpack.js?ts=1687365061359:677:31)
    at __webpack_require__ (webpack.js?ts=1687365061359:37:33)
    at fn (webpack.js?ts=1687365061359:332:21)
    at eval (index.es.js:6:84)
    at ./node_modules/@walletconnect/universal-provider/dist/index.es.js (index.js?ts=1687365061359:929:1)
    at options.factory (webpack.js?ts=1687365061359:677:31)
    at __webpack_require__ (webpack.js?ts=1687365061359:37:33)
    at fn (webpack.js?ts=1687365061359:332:21)
    at eval (index.es.js:12:91)
    at ./node_modules/@walletconnect/ethereum-provider/dist/index.es.js (index.js?ts=1687365061359:260:1)
    at options.factory (webpack.js?ts=1687365061359:677:31)
    at __webpack_require__ (webpack.js?ts=1687365061359:37:33)
    at fn (webpack.js?ts=1687365061359:332:21)
    at eval (index.jsx:7:90)
    at ./src/pages/index.jsx (index.js?ts=1687365061359:1047:1)
    at options.factory (webpack.js?ts=1687365061359:677:31)
    at __webpack_require__ (webpack.js?ts=1687365061359:37:33)
    at fn (webpack.js?ts=1687365061359:332:21)
    at eval (?9c60:5:16)
    at eval (route-loader.js:233:51)
eval @ index.es.js:1
./node_modules/@walletconnect/types/dist/index.es.js @ index.js?ts=1687365061359:918
options.factory @ webpack.js?ts=1687365061359:677
__webpack_require__ @ webpack.js?ts=1687365061359:37
fn @ webpack.js?ts=1687365061359:332
eval @ index.es.js:68
./node_modules/@walletconnect/core/dist/index.es.js @ index.js?ts=1687365061359:216
options.factory @ webpack.js?ts=1687365061359:677
__webpack_require__ @ webpack.js?ts=1687365061359:37
fn @ webpack.js?ts=1687365061359:332
eval @ index.es.js:27
./node_modules/@walletconnect/sign-client/dist/index.es.js @ index.js?ts=1687365061359:797
options.factory @ webpack.js?ts=1687365061359:677
__webpack_require__ @ webpack.js?ts=1687365061359:37
fn @ webpack.js?ts=1687365061359:332
eval @ index.es.js:6
./node_modules/@walletconnect/universal-provider/dist/index.es.js @ index.js?ts=1687365061359:929
options.factory @ webpack.js?ts=1687365061359:677
__webpack_require__ @ webpack.js?ts=1687365061359:37
fn @ webpack.js?ts=1687365061359:332
eval @ index.es.js:12
./node_modules/@walletconnect/ethereum-provider/dist/index.es.js @ index.js?ts=1687365061359:260
options.factory @ webpack.js?ts=1687365061359:677
__webpack_require__ @ webpack.js?ts=1687365061359:37
fn @ webpack.js?ts=1687365061359:332
eval @ index.jsx:7
./src/pages/index.jsx @ index.js?ts=1687365061359:1047
options.factory @ webpack.js?ts=1687365061359:677
__webpack_require__ @ webpack.js?ts=1687365061359:37
fn @ webpack.js?ts=1687365061359:332
eval @ ?9c60:5
eval @ route-loader.js:233
setTimeout (async)
hydrate @ index.js:637
await in hydrate (async)
eval @ next-dev.js:48
Promise.then (async)
eval @ next-dev.js:42
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1687365061359:181
options.factory @ webpack.js?ts=1687365061359:677
__webpack_require__ @ webpack.js?ts=1687365061359:37
__webpack_exec__ @ main.js?ts=1687365061359:1160
(anonymous) @ main.js?ts=1687365061359:1161
webpackJsonpCallback @ webpack.js?ts=1687365061359:1262
(anonymous) @ main.js?ts=1687365061359:9
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1760 Uncaught TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (react.development.js:1760:1)
    at ReactDevOverlay (client.js:876:956)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
useReducer @ react.development.js:1760
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>. 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
errorHydratingContainer @ react-dom.development.js:11473
recoverFromConcurrentError @ react-dom.development.js:25846
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1760 Uncaught TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (react.development.js:1760:1)
    at ReactDevOverlay (client.js:876:956)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
useReducer @ react.development.js:1760
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 The above error occurred in the <ReactDevOverlay> component:

    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:877:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:92:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:196:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:374:11)

React will try to recreate this component tree from scratch using the error boundary you provided, Container.
console.error @ client.js:1
window.console.error @ next-dev.js:27
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Container: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:92:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:196:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:374:11)
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
callback @ react-dom.development.js:18778
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:19849:1)
    at beginWork (react-dom.development.js:21615:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
updateHostRoot @ react-dom.development.js:19849
beginWork @ react-dom.development.js:21615
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1760 Uncaught TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (react.development.js:1760:1)
    at ReactDevOverlay (client.js:876:956)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopConcurrent (react-dom.development.js:26543:1)
    at renderRootConcurrent (react-dom.development.js:26505:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
useReducer @ react.development.js:1760
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react.development.js:226
error @ react.development.js:200
resolveDispatcher @ react.development.js:1726
useReducer @ react.development.js:1759
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1760 Uncaught TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (react.development.js:1760:1)
    at ReactDevOverlay (client.js:876:956)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
useReducer @ react.development.js:1760
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 The above error occurred in the <ReactDevOverlay> component:

    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:877:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:92:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:196:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:374:11)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.error @ client.js:1
window.console.error @ next-dev.js:27
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:26923 Uncaught TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (react.development.js:1760:1)
    at ReactDevOverlay (client.js:876:956)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
useReducer @ react.development.js:1760
ReactDevOverlay @ client.js:876
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
index.js:447 Uncaught (in promise) Error: Cancel rendering route
    at lastRenderReject (index.js:447:27)
    at eval (index.js:438:13)
    at new Promise (<anonymous>)
    at doRender (index.js:436:27)
    at renderError (index.js:272:16)
    at Object.fn (index.js:229:13)
    at Container.componentDidCatch (index.js:95:20)
    at Container.callback (react-dom.development.js:18768:1)
    at callCallback (react-dom.development.js:13923:1)
    at commitUpdateQueue (react-dom.development.js:13944:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23364:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
    at commitLayoutEffects_begin (react-dom.development.js:24674:1)
    at commitLayoutEffects (react-dom.development.js:24612:1)
    at commitRootImpl (react-dom.development.js:26823:1)
    at commitRoot (react-dom.development.js:26682:1)
    at finishConcurrentRender (react-dom.development.js:25892:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25809:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
l
```

**Comment by 0xAsimetriq** [comment]
Is this with yarn v1? It's known to have errors with sub-dependency resolutions, some workarounds that worked for devs are

1. Remove package-lock.json file and install with yarn again
2. Use npm / pnpm / yarn@latest

**Comment by 0xAsimetriq** [comment]
Closing for now, feel free to re-open. All examples were updated and tested to work. Left advice above.

**Comment by ChrisCates** [comment]
Thanks, I ended up migrating to a different library. But I will upgrade
yarn to improve dependency management.


-- 
PGP: 6DFCF0BC43CAC026
------------------------------------------
This email is intended only for the person or entity to which it is
addressed and may contain information that is privileged, confidential or
otherwise protected from disclosure. Dissemination, distribution, or
copying of this email or the information herein by anyone other than the
intended recipient, or an employee or agent responsible for delivering the
message to the intended recipient, is prohibited.
