### ISSUE TITLE
[Test] Missing E2E tests

### ISSUE THREAD

**Issue by valamidev** [WalletConnect/web3modal-examples#32]
While checking following examples, I found out that:

`walletconnect-modal-ethereum-provider-html`
`web3modal-wagmi-html`

are even have syntax error in the Javascript output produced by Vite.

Highly recommend, to add E2E tests for the repository.

**Comment by 0xAsimetriq** [comment]
@valamidev can you point / showcase concrete error please?

**Comment by valamidev** [comment]
> @valamidev can you point / showcase concrete error please?

Sure e.g.:

`walletconnect-modal-ethereum-provider-html`

```
main.js:20 {context: 'core'} 'global is not defined'
main.js:20 {context: 'client'} 'global is not defined'
main.js:43 ReferenceError: global is not defined
    at De (jsonrpc.ts:29:23)
    at Me (jsonrpc.ts:29:23)
    at qn (jsonrpc.ts:29:23)
    at Pt2.createProvider (index.ts:5:16)
    at async Pt2.init (index.ts:5:16)
    at async Z2.initialize (index.ts:5:16)
    at async Z2.start (index.ts:5:16)
    at async M3.initialize (index.ts:5:16)
    at async M3.init (index.ts:5:16)
    at async hr.createClient (lodash.js:10:1)

```
